version: 0.0
os: linux

files:
  - source: / 
    destination: /home/ubuntu/flaskapp 
    overwrite: yes 

permissions:
  - object: / 
    pattern: "**"
    owner: ubuntu 
    group: ubuntu 

hooks:
  AfterInstall:
    - location: scripts/set_env_vars.sh # 환경 변수
      timeout: 60 
      runas: root # 환경 변수 설정은 root 권한으로 실행
    - location: scripts/stop.sh 
      timeout: 60 
      runas: ubuntu 
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
