name: Build and Deploy Flask to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: looglereal-github-actions-s3-bucket
  APPLICATION_NAME: looglereal-flask
  DEPLOYMENT_GROUP: looglerealflask-codedeploy-deployment-group
  REGION: ${{ secrets.AWS_REGION }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEM_API_KEY: ${{ secrets.GEM_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Create .env file
        run: |

      - name: Make Zip File
        run: |
          . venv/bin/activate
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$APPLICATION_NAME/$GITHUB_SHA.zip
          
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name $$APPLICATION_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $DEPLOYMENT_GROUP  \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$APPLICATION_NAME/$GITHUB_SHA.zip

                
