name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: loogle-github-actions-s3-bucket
  APPLICATION_NAME: ${{ secrets.CODEDEPLOY_APPLICATION }}
  DEPLOYMENT_GROUP: ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }}
  REGION: ${{ secrets.AWS_REGION }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEM_API_KEY: ${{ secrets.GEM_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Zip the application
      run: |
        zip -r flaskapp.zip . 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ secrets.AWS_REGION }}  

    # (5) 빌드 결과물을 S3 버킷에 업로드
    - name: Upload to AWS S3
      run: |
        aws deploy push \
          --application-name $APPLICATION_NAME \
          --ignore-hidden-files \
          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --source .

    # (6) S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
    - name: Deploy to AWS EC2 from S3
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name $DEPLOYMENT_GROUP \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip \
          --region $REGION
          

